    selenium-hub:
        image: selenium/hub
        ports:
            - 4444:4444
    
    firefox:
        image: selenium/node-firefox-debug
        links:
            - selenium-hub:hub
        ports:
            - 4446:5900
    
    chrome:
        image: selenium/node-chrome-debug
        links:
            - selenium-hub:hub
        ports:
            - 4445:5900